config/routes.rb
Rails.application.routes.draw do
  

  get 'todos', to: 'todo#index'
  get   'todoshow',      to: 'todo#show'

  root 'todo#show'

  post   'todocreate',      to: 'todo#create'
  delete  'tododelete:id',  to: 'todo#destroy', as: 'tododelete'
  patch  'todoupdate:id',  to: 'todo#update', as: 'todoupdate'
  post   'todoedit:id',   to: 'todo#edit',     as: 'todoedit'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :todos, dependent: :destroy
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @proj=Project.new
    @projs=Project.all
  end

  def edit
  end

  def create
    @proj = Project.new(project_params)
    respond_to do |format|
      if @proj.save
        format.html { redirect_to projects_path }
      else
        format.html { render :index , notice: 'Добавлено'}
      end
    end
  end

  def update
    respond_to do |format|
      if @proj.update(project_params)
         format.html { redirect_to projects_path }
      else
        format.html { render :edit , notice: 'Обновлено' }
      end
    end
  end

  def destroy
    @proj.destroy
    respond_to do |format|
      format.html { redirect_to projects_path , notice: 'Удалено' }      
    end
  end
private
   def project_params
      return params.require(:project).permit(:title)
   end

  def set_tod
    @proj = Project.find(params[:id].to_i) rescue nil?
    if @proj==false
      redirect_to  errors_path
    end
  end

end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
 before_action :set_tod, only: [:edit, :update, :destroy]
  def index
  	@todo=Todo.new
  end
  def show
  	@proj=Project.all
  end
  def edit 
 	
  end

  def create
    @todo = Todo.new(todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to todoshow_path }
      else
        format.html { render :show }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todoshow_path }
      else
        format.html { render :edit  }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
        format.html { redirect_to todoshow_path }
    end
  end
private
   def todo_params
      return params.require(:todo).permit(:text,:isComplete,:project_id)
   end

  def set_tod
    @todo = Todo.find(params[:id].to_i) rescue nil?
    if @todo==false
      redirect_to  errors_path
    end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
   <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'  %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/edit.html.erb
<% provide(:title, 'задачи') %>
<style>

</style>
<div class="login-page">
  <div class="form">
    <p style="color:black; font-size:14px ">Добавления задачи в проект</p>
      <%= form_for(@todo,  url:"/todoupdate#{(@todo.id)}") do |f| %>
	<%=f.select :project_id,options_for_select(Project.all.collect{ |u| [u.title,u.id]},selected:@todo.project_id)  %>
        <%= f.text_field :text,placeholder: 'Названия задачи' %>
<label style='color:black'>
задача выполнен
        <%= f.check_box :isCompleted %>
</label>
        <%= f.submit 'Редактировать', class: "button" %>
    <% end %>
  </div>
  
</div>

app/views/todo/index.html.erb
<% provide(:title, 'Категории') %>

<div class="login-page">
  <div class="form">
    <p style="color:black; font-size:14px ">Добавления задачи в проект</p>
      <%= form_for(@todo,  url:'/todocreate') do |f| %>
	<%=f.select :project_id,options_for_select(Project.all.collect{ |u| [u.title,u.id]})  %>
        <%= f.text_field :text,placeholder: 'Названия задачи' %>
<label style='color:black'>
задача выполнен
        <%= f.check_box :isCompleted %>
</label>
        <%= f.submit 'Добавить', class: "button" %>
    <% end %>
  </div>
  
</div>

app/views/todo/show.html.erb
<% provide(:title, 'Категории') %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin: 0px;background:  deepskyblue;">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="glyphicon glyphicon-plus"></span>
    </button>    
    <a class="navbar-brand" href="#">Задачи</a>    
  </div>
  <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      <li>
      
      <a id="modal-127356" href="#modal-container-127356" role="button" class="btn" data-toggle="modal">
        <span class="glyphicon glyphicon-plus"></span>
      </a>
      </li>      
    </ul>
  </div>
</nav>

<div class="container-fluid" style="margin-top: 7%;">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
      <%@proj.each do |cat| %>
        <div class="col-md-4">
          <div class="list-group">
             <a href="#" class="list-group-item"><%=cat.title%></a>
    <% Todo.where(project_id:cat.id).each do |tod|  %>    
            <div class="list-group-item">
              <h4 class="list-group-item-heading">
                                                
                <%if tod.isCompleted==true%>
                <label>
                <input ondblclick='func("id<%=tod.id%>")' class="btn btn-primary"  name="<%tod.id%>" type="checkbox" value='1' checked/>&nbsp;<strike><%=tod.text%> </strike>
                </label>
               <%else%>
                <label>
                <input class="btn btn-primary" ondblclick='func("id<%=tod.id%>")' name="<%tod.id%>" type="checkbox" value='1'/>&nbsp;<%=tod.text%>   
                </label>              
                <%end%>                                 
					<div id="id<%=tod.id%>" style='display: none;'>
					                <hr>
					                    <%= link_to  "Удалить" ,tododelete_path(tod.id),method: :delete %>/
					    		<%= link_to  "Редактировать" ,todoedit_path(tod.id),method: :post %>

					 </div>

              </h4> 
            </div>
            <% end %>
            
          </div>
        </div>
        <% end %>
</div>    
      
      <div class="modal fade" id="modal-container-127356" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
               
              <button type="button" class="close" data-dismiss="odal" aria-hidden="true">
                ×
              </button>
              <h4 class="modal-title text-centre" id="myModalLabel">
                Новая задача
              </h4>
            </div>
            <div class="modal-body">
                  <%@todo =Todo.new%>
          <%= form_for(@todo,  url:'/todocreate') do |f| %>
          <div class="form-group">
            <%= f.text_field :text,placeholder: 'Название задачи',class:'form-control' %>
            <div class="select">
          <%=f.select(:project_id,options_for_select(Project.all.collect{ |u| [u.title,u.id]}),{},{:class=>"form-control"})  %>  
          </div>
        </div>
        <% end %>
  </div>
           <div class="modal-footer">
           <div style="text-align: center;">

           <%= link_to "OK", '#', id: "li",class:'btn',style:"width: 40%;background:  deepskyblue;"%>
           
      	<a href="#" id="formout" class='btn' data-dismiss="modal" style="width: 40%; height='50px' ;background:  white;">Отмена</a>  &nbsp;&nbsp;
      	  </div>
         </div>
           
               
      </div>
            </div>

          </div>
          
        </div>
        
      </div>
      
    </div>
  </div>
</div>      
<script type="text/javascript">
	function func(argument) 
	{
		if (document.getElementById(argument).style.display=="none") {
			document.getElementById(argument).style.display="block";
		}else
		document.getElementById(argument).style.display="none";

		
	}
</script>